version: "3.9"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user: ec2-user
        uid: 1000
    image: intern-php
    container_name: intern-php-app
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
